name: Sync ServiceNow Knowledge

on:
  schedule:
    - cron: '0 */6 * * *'

  workflow_dispatch:

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5

        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Sync ServiceNow KB
        env:
          SNOW_INSTANCE: ${{ secrets.SNOW_INSTANCE }}
          SNOW_USER: ${{ secrets.SNOW_USER }}
          SNOW_PASSWORD: ${{ secrets.SNOW_PASSWORD }}

        run: |
          python sync/servicenow_sync.py

      - name: Commit Updated Knowledge
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add knowledge/
          git commit -m "Auto sync ServiceNow knowledge" || echo "No changes"
          git push
      - name: rename to remove invalid characters from python file name 
        run: |
          python sync/rename_invalid_files.py
